# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install:
  - travis_retry pip install pytz
  - pip install -U .
  - pip install flake8

before_script:
  - flake8 marshmallow

script: python setup.py test
